version: '3.8'

networks:
  records:
    driver: bridge

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - database:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=records
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - PG_DB_URL=postgresql+asyncpg://
    networks:
      - records

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0"
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - type: volume
        source: old_media
        target: /api/media/wav/
        volume:
          nocopy: false
      - type: volume
        source: new_media
        target: /api/media/mp3/
        volume:
          nocopy: false
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - records

  ffmpeg:
    container_name: ffmpeg
    image: jrottenberg/ffmpeg
    ports:
      - "29002:8000"
    tty: true
    entrypoint: "bash"
    networks:
      - records

volumes:
  database:
  old_media:
  new_media: