version: '3.8'

networks:
  b2c:
    driver: bridge

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - database:/var/lib/postgresql/data/
    networks:
      - b2c
    env_file:
      - .env

  app:
    build: .
    command: uvicorn main:application --host 0.0.0.0
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - type: volume
        source: old_media
        target: /api/media/wav/
        volume:
          nocopy: false
      - type: volume
        source: new_media
        target: /api/media/mp3/
        volume:
          nocopy: false
    networks:
      - b2c
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env

  ffmpeg:
    container_name: b2c-ffmpeg
    image: jrottenberg/ffmpeg
    tty: true
    networks:
      - b2c
    ports:
      - "29002:29000"
    entrypoint: "bash"

volumes:
  database:
  old_media:
  new_media: